### PR TITLE
ALV-175: Apply "Chroot" configuration to filetransfer operations

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
Just to double check - the idea presented in the [ALV-175](https://northerntech.atlassian.net/browse/ALV-175) is that the nt-connect will automatically add CONNECT_CHROOT value as a prefix to all the downloads and uploads, right?
I tested it on my raspberry pi and it was not working; did you test it?

**Comment by kjaskiewiczz** [comment]
also, if the file already exists, I'm getting `Error uploading file to device. lstat /host/alvaldi.txt: no such file or directory` error message

**Comment by alfrunes** [comment]
> also, if the file already exists, I'm getting `Error uploading file to device. lstat /host/alvaldi.txt: no such file or directory` error message

The implementation is definitely broken. It's only evaluating the constraint without applying the actual chroot local path.

**Comment by alfrunes** [comment]
@kjaskiewiczz I updated the implementation and refactored the path expansions to [session/model/filetransfer.go](https://github.com/NorthernTechHQ/nt-connect/blob/6480229567ca650e0cf0d6f0fcae0368914049b8/session/model/filetransfer.go#L51).

**Pull request merged**
