### PR TITLE
Dependency upgrades

### PR DESCRIPTION
**Pull request by alfrunes**
* github.com/gorilla/websocket v1.5.0 -> v1.5.1
* github.com/mendersoftware/go-lib-micro v0.0.0-20230808081028-48c0b853fd99 -> v0.0.0-20231031082957-e2bce6ff3edd
* github.com/urfave/cli/v2 v2.0.0-00010101000000-000000000000 -> v2.25.7

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
I think we are lacking some checks in this repository - gitlab pipeline failed, nobody approved and I can still merge the PR.

**Comment by olehermanse** [comment]
@kjaskiewiczz Thanks, I've added some basic branch protection.

**Review by kjaskiewiczz — APPROVED** [review]
looks good, but the license checker is not happy

**Review by olehermanse — CHANGES_REQUESTED** [review]
LGTM, except for CI.

**Comment by alfrunes** [comment]
I dropped the commit removing the `vendor` folder and `LIC_FILES_CHKSUM.sha256` since this is a device component and requires compatibility with Yocto (as pointed out [here](https://github.com/mendersoftware/mendertesting/pull/302)).

**Review by olehermanse — APPROVED** [review]

**Pull request merged**
